apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: nginx-deployment
  minReplicaCount:  1
  maxReplicaCount:  3 
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Bangkok  
      start: 30 * * * *       
      end: 45 * * * *         
      desiredReplicas: "10"
